before_install:
- sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng
script:
- mkdir _build
- pdflatex -output-directory _build --jobname=reglement_interieur ReglementInterieur.tex
deploy:
  provider: releases
  api_key:
    secure: kyiKH/zMk1dOrettyNyQ1wZobp6eccys9V8DTsx94/+T3wabTb7FQAZv3QQ1dFjXHG13IllxVYbGewF2SVBow8/5FqVVzQFR4zUacCGEFDS7CwMYD4NH3oz1GIxlmKH1IHwtVM5K9Q+0YEw0R++FGe4AwLOZhoBS1o00FyPNoAQO+7rBBppcU3mSy8wExlzVS8b+331OTMistpjVZsNjk1BLBekDzgmROmb7qHUJtkpN1sNh9QwAQIySEnt+gE3PrlZQ/zVD4IULfzAPvhA1mOrTezVGc2sBnDvaBKU/v/kwD9dFzB9mzl3dMLZiNHNatfydww7RBCtt6kqd7wu7RpvN+gtPxAyAqMQByVWARK9ghrT7vLV5xloE1XzIqztkD5zjqGjGW2fYBuPeQU9P/DOX6NuLOgOS7ojqf6WeYpB2TeHblGcctewS0qDTxmH6WgVtlLFV74GR681mKVOlJJ+xD0Y0CxY9k63+HbyXkUKewxfhrLlURt2k+FuDDKnKmTCSpI+bWAsWgmsJG4tgI1uOwSnVu6ZEdvJoyyDVTq94HTEUywCpqUZUXmUUO8Z1bLp/nCOtyJDgxBeGOQW6AcmacLk3UvOrSP5X1iYuxcs66Dw0Ez63WYQ470CoQvOBZqIuxCuxPqu4A/CHDqXyTVgcMJ9dUr4xya2EG3D5IB8=
  file: _build/reglement_interieur.pdf
  skip_cleanup: true
  on:
    repo: rezoleo/reglement_interieur
    tags: true
