before_install:
- sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng
script:
- mkdir _build
- pdflatex -output-directory _build --jobname=reglement_interieur règlement_intérieur.tex
deploy:
  provider: releases
  api_key:
    secure: GZtYoKsZCBGImmTpiGm+JjmU889xP01Lk3zfPZl5EqV85fVdECZiY40P89aTEUs/t1xaVWzzC4j0FFEGwrBipHeBgzGW4K86XQycbG7+sfddvcXbYz7nQAMiYme2liig3m6nEPO2cLhK6f8EAOOBw3W+R6AUv5/ZlCr88aru7fVSGmTcx/V/fgecpqPP0nJ5Ip4LmR4MmlTLMx5h7x44iBMt8x4MTsA/3/4b/cLZQA5ERPHdRbq4x7Dljw5hVvS6Kg1MPxsKlfPAQwLfwfU1vdD50ImnCNaSwCs5k6Ia6GSnodDZI3hXj9GffxOmurAk0JU7MGmBJUVR+hu/+H2X2saK7OM4neE55AMdfVPgZhAFS4gcsOtPPluWxAiDfPseJxSFjHMkEy+vBCTUoYOv4aS0rMqKT78m04wJy8QVcEghuw+BuvzYbecl36XXTpuiclp5Uy0Ndo7p49OTCRjA5/vO3+6wVvAJrCKXS9suN2sG8DOoUabcaBwPjcibosirhrxNyrjh1FKyLr2IAIa3CNQi42t7lzXX21vZn4AX39fpsykQXjDzu0jkHOk1XG/sjT+vPBA7+rGAFgdFcU+rZrgN2Ak8br6XXs31DLQ1Jto8P4GELsdRNwWJdsh7TqOmMe9YQdEQYp4NjNP6uKKdU7tGq2sIImsMoDLR2YkO8Xg=
  file: _build/règlement_intérieur.pdf
  on:
    repo: rezoleo/reglement_interieur
    tags: true