name: Build LaTeX document

on:
  push:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ReglementInterieur.tex
          extra_fonts: ./fonts/*.ttf

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Compiled LaTeX document
          path: "*.pdf"
          if-no-files-found: error
          retention-days: 5

      # Upload pdf file in GitHub release
      - if: ${{ github.event_name == 'release'}}
        name: Upload PDF to release
        uses: svenstaro/upload-release-action@2b9d2847a97b04d02ad5c3df2d3a27baa97ce689 # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.pdf"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "Compiled LaTeX document"


